arm:
   # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
  
  # Position Controllers ---------------------------------------
  joint_one_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_one
    pid: {p: 0.3, i: 0.3, d: 0.075}
  # Position Controllers ---------------------------------------
  joint_two_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_two
    pid: {p: 0.3, i: 0.3, d: 0.075}

 
